// events.js
// Data for AI Week 2026 events

const events = [
  // Monday, March 23
  {
    id: "mon-local-llm",
    day: "Monday",
    date: "2026-03-23",
    title: "Local and Personal Language Models",
    startTime: "On-demand",
    endTime: null,
    location: "Gen AI site | Online",
    modality: "Pre-recorded",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Syed Hasib AKhter Faruqui; SHSU TLC AI Faculty Fellow, Assistant Professor of Department of Engineering Technology",
    notes: "Pre-recorded and posted to the GenAI site.",
    linkLabel: "View Online",
    link: "https://www.youtube.com/watch?v=z_OFPo4zXi4",
    tags: ["Workshop", "Asynchronous"]
  },
  {
    id: "mon-gartner",
    day: "Monday",
    date: "2026-03-23",
    title: "AI and Your Future: Opportunities and Challenges Ahead",
    startTime: "10:00 am",
    endTime: null,
    location: "AB1 307",
    modality: "In person",
    description: "This presentation examines how AI is reshaping work and education, including its impact on entry-level roles and human-AI collaboration. It offers a student guide and key leadership skills for succeeding in an AI-driven world.",
    modOrTrainerLabel: "Speaker",
    modOrTrainer: "John Baker",
    notes: "",
    link: null,
    tags: ["Faculty", "Staff", "Students", "In person"]
  },
  {
    id: "mon-ai-writing-course",
    day: "Monday",
    date: "2026-03-23",
    title: "Developing and Teaching an AI Writing Course",
    startTime: "2:00 pm",
    endTime: "3:00 pm",
    location: "LDB 339",
    modality: "In person",
    description: "An overview of developing an AI writing course and insights from students’ effective practices and common challenges.",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "Yingying Tang, SHSU AI Faculty Fellow, Assistant Professor of Technical Communication",
    notes: "",
    link: null,
    tags: ["Teaching", "Faculty focus", "In person"]
  },
  {
    id: "mon-ethical-ai-learning-teaching",
    day: "Monday",
    date: "2026-03-23",
    title: "The Ethical Use of AI in Learning and Teaching.",
    startTime: "3:30 pm",
    endTime: "4:30 pm",
    location: "Zoom",
    modality: "Online",
    description: "A focused discussion on ethical AI use in learning and teaching, including common student and faculty challenges, practical guardrails, and policy-informed guidelines for responsible use.",
    modOrTrainerLabel: "Presenters",
    modOrTrainer: "Elizabeth Gross and Tracey Hodges",
    notes: "Meeting ID: 856 3145 9059 | Passcode: genAICoP",
    link: "https://shsu.zoom.us/j/85631459059",
    tags: ["Teaching", "Ethics", "Online"]
  },

  // Tuesday, March 24
  {
    id: "tue-gemini-notebooklm",
    day: "Tuesday",
    date: "2026-03-24",
    title: "Intro to Gemini and NotebookLM",
    titleTag: "Faculty & Staff Only",
    startTime: "9:30 am",
    endTime: "11:00 am",
    location: "Teams",
    modality: "Online",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Britney Norris (IT)",
    notes: "",
    linkLabel: "Register",
    link: "https://samhouston.csod.com/samldefault.aspx?ouid=1&returnUrl=%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253dlodetails%2526lo%253dca934c65-f031-4b15-a723-51872fd5bbba",
    tags: ["Training", "Tools", "Faculty support"]
  },
  {
    id: "tue-ai-research-grad",
    day: "Tuesday",
    date: "2026-03-24",
    title: "AI in Research: Reliability, Ethics and Disclosure (Graduate Student Seminar)",
    startTime: "2:00 pm",
    endTime: "3:00 pm",
    location: "Zoom",
    modality: "Online",
    modOrTrainer: "",
    notes: "Register with TGPS.",
    link: null,
    tags: ["Research", "Graduate students"]
  },
  {
    id: "tue-ai-research-main",
    day: "Tuesday",
    date: "2026-03-24",
    title: "AI in Research: Reliability, Ethics, and Disclosure",
    startTime: "3:30 pm",
    endTime: "4:30 pm",
    location: "Zoom",
    modality: "Online",
    modOrTrainer: "",
    notes: "",
    link: "https://shsu.zoom.us/j/83780076939",
    tags: ["Research"]
  },

  // Wednesday, March 25
  {
    id: "wed-promises-threats",
    day: "Thursday",
    date: "2026-03-26",
    title: "Promises and Threats: Artificial Intelligence in Arts & Media",
    startTime: "10:30 am",
    endTime: "12:00 noon",
    location: "GPAC 170",
    modality: "In person",
    description: "Roundtable with faculty discussing their use of AI in creative practices.",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Michael Henderson",
    notes: "",
    link: null,
    flyerLink: "Artsflyer.pdf",
    flyerLabel: "View flyer",
    tags: ["Roundtable", "Arts & Media", "Creative", "In person"]
  },
  {
    id: "wed-copilot-chat",
    day: "Wednesday",
    date: "2026-03-25",
    title: "MS Copilot Chat Training",
    titleTag: "Faculty & Staff Only",
    startTime: "9:30 am",
    endTime: "11:00 am",
    location: "Virtual",
    modality: "Online",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Britney Norris (IT)",
    notes: "",
    linkLabel: "Register",
    link: "https://samhouston.csod.com/samldefault.aspx?ouid=1&returnUrl=%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253dlodetails%2526lo%253de14f2f92-4ed0-41c3-b450-db6365da4f28",
    tags: ["Training", "Tools", "Faculty support"]
  },
  {
    id: "wed-create-or-generate",
    day: "Wednesday",
    date: "2026-03-25",
    title: "Create or Generate: Crafting and Gossiping About Generative AI",
    startTime: "6:30 pm",
    endTime: "8:30 pm",
    location: "Newton Gresham Library Main Lobby",
    modality: "In person",
    modOrTrainer: "",
    notes: "No registration needed.",
    flyerLink: "Createflyer.pdf",
    flyerLabel: "View flyer",
    link: null,
    tags: ["Library", "Evening event", "In person"]
  },

  // Thursday, March 26
  {
    id: "thu-prompt-workshop",
    day: "Thursday",
    date: "2026-03-26",
    title: "Prompting for Precision: Designing Effective AI Queries in Higher Education",
    startTime: "10:00 am",
    endTime: "11:00 am",
    location: "Zoom",
    modality: "Online",
    description: "Learn how to write effective AI prompts to support teaching, research, and faculty workflows. This session provides practical strategies and ready-to-use examples you can apply immediately.",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "Dr. Ashley L. Brittain, SHSU AI Faculty Fellow, Assistant Professor-School of Teaching and Learning",
    notes: "",
    link: "https://shsu.zoom.us/j/5345325402",
    flyerLink: "Ashleyflyer.pdf",
    flyerLabel: "View flyer",
    tags: ["Workshop", "Faculty", "Prompting"]
  },
  {
    id: "thu-middle-ground",
    day: "Thursday",
    date: "2026-03-26",
    title: "Middle Ground: Bearkats Talk AI",
    startTime: "11:00 am",
    endTime: "1:00 pm",
    location: "LSC Room 241",
    modality: "In person",
    modOrTrainerLabel: "Panelist",
    modOrTrainer: "Syed Hasib AKhter Faruqui, Bina Ajay, Yingying Tang",
    notes: "",
    link: null,
    tags: ["Panel", "Students", "Faculty", "In person"]
  },
  {
    id: "thu-skeptics-panel",
    day: "Wednesday",
    date: "2026-03-25",
    title: "Skeptics Panel",
    startTime: "12:00 pm",
    endTime: "1:30 pm",
    location: "NGL 402",
    modality: "In person",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "Erin Owens",
    notes: "Panelists: Benjamin Mitchell-Yellin, Syed Faruqui, Ren Oliver, and Jay Neupane",
    link: null,
    tags: ["Panel", "In person"]
  },
  {
    id: "thu-blackboard-design-assistant",
    day: "Thursday",
    date: "2026-03-26",
    title: "AI Design Assistant for Blackboard Webinar",
    startTime: "1:00 pm",
    endTime: null,
    location: "Online",
    modality: "Online",
    modOrTrainer: "SHSU Online Instructional Development and Support",
    notes: "",
    linkLabel: "Register",
    link: "https://wkf.ms/4rP6d1Z",
    tags: ["Webinar", "Blackboard", "Faculty support"]
  },
  {
    id: "thu-coba-academic-affairs-panel",
    day: "Thursday",
    date: "2026-03-26",
    title: "COBA Sponsored Academic Affairs AI Panel",
    startTime: "3:00 pm",
    endTime: "4:30 pm",
    location: "LSC 323",
    modality: "In person",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "Dr. Shani Robinson",
    notes: "",
    flyerLink: "coba new.png",
    flyerLabel: "View Flyer",
    link: null,
    tags: ["Panel", "Academic affairs", "In person"]
  },
  {
    id: "thu-academic-affairs-panel",
    day: "Tuesday",
    date: "2026-03-24",
    title: "Academic Integrity in the Age of AI Webinar",
    startTime: "12:00 pm",
    endTime: null,
    location: "Online",
    modality: "Online",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "SHSU Online Instructional Development and Support",
    notes: "",
    linkLabel: "Register",
    link: "https://wkf.ms/4rP6d1Z",
    tags: ["Webinar", "Academic integrity", "Faculty support"]
  },

  // Friday, March 27
  {
    id: "thu-licensed-copilot",
    day: "Friday",
    date: "2026-03-27",
    title: "Licensed MS Copilot Training",
    titleTag: "Faculty & Staff Only",
    startTime: "9:30 am",
    endTime: "11:00 am",
    location: "Teams",
    modality: "Online",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Britney Norris (IT)",
    notes: "",
    linkLabel: "Register",
    link: "https://samhouston.csod.com/samldefault.aspx?ouid=1&returnUrl=%252fDeepLink%252fProcessRedirect.aspx%253fmodule%253dlodetails%2526lo%253d55a0d32d-71a5-4209-a4f8-f34fadb2eb55",
    tags: ["Training", "Tools", "Faculty support"]
  }
];

// If Codex uses ES modules, it can change this to `export default events;`
