// events.js
// Data for AI Week 2026 events

const events = [
  // Monday, March 23
  {
    id: "mon-local-llm",
    day: "Monday",
    date: "2026-03-23",
    title: "Local and Personal Language Models",
    startTime: null,
    endTime: null,
    location: "Gen AI site",
    modality: "Pre-recorded",
    modOrTrainer: "Syed",
    notes: "Pre-recorded and posted to the Gen AI site.",
    link: null,
    tags: ["Workshop", "Asynchronous"]
  },
  {
    id: "mon-gartner",
    day: "Monday",
    date: "2026-03-23",
    title: "Gartner AI Presentation",
    startTime: "10:00 am",
    endTime: null,
    location: "TBD",
    modality: "In person",
    modOrTrainer: "",
    notes: "",
    link: null,
    tags: ["Talk"]
  },
  {
    id: "mon-ai-writing-course",
    day: "Monday",
    date: "2026-03-23",
    title: "Developing and Teaching an AI Writing Course",
    startTime: "2:00 pm",
    endTime: "3:00 pm",
    location: "LDB 339 (36 seats), FTF",
    modality: "In person",
    description: "An overview of developing an AI writing course and insights from students’ effective practices and common challenges.",
    modOrTrainerLabel: "Moderator",
    modOrTrainer: "Yingying Tang, SHSU AI Faculty Fellow, Assistant Professor of Technical Communication",
    notes: "",
    link: null,
    tags: ["Teaching", "Faculty focus"]
  },

  // Tuesday, March 24
  {
    id: "tue-gemini-notebooklm",
    day: "Tuesday",
    date: "2026-03-24",
    title: "Intro to Gemini and NotebookLM",
    startTime: "9:30 am",
    endTime: "11:00 am",
    location: "Teams",
    modality: "Online",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Britney Norris (IT)",
    notes: "",
    link: null,
    tags: ["Training", "Tools"]
  },
  {
    id: "tue-ai-research-grad",
    day: "Tuesday",
    date: "2026-03-24",
    title: "AI in Research: Reliability, Ethics and Disclosure (Graduate Student Seminar)",
    startTime: "2:00 pm",
    endTime: "3:00 pm",
    location: "Zoom",
    modality: "Online",
    modOrTrainer: "",
    notes: "Register with TGPS.",
    link: null,
    tags: ["Research", "Graduate students"]
  },
  {
    id: "tue-ai-research-main",
    day: "Tuesday",
    date: "2026-03-24",
    title: "AI in Research: Reliability, Ethics, and Disclosure",
    startTime: "3:30 pm",
    endTime: "4:30 pm",
    location: "Zoom",
    modality: "Online",
    modOrTrainer: "",
    notes: "",
    link: "https://shsu.zoom.us/j/83780076939",
    tags: ["Research"]
  },

  // Wednesday, March 25
  {
    id: "wed-promises-threats",
    day: "Thursday",
    date: "2026-03-26",
    title: "Promises and Threats: Artificial Intelligence in Arts & Media",
    startTime: "10:30 am",
    endTime: "12:00 noon",
    location: "GPAC 170",
    modality: "In person",
    description: "Roundtable with faculty discussing their use of AI in creative practices.",
    modOrTrainer: "Michael Henderson",
    notes: "",
    link: null,
    flyerLink: "Artsflyer.pdf",
    flyerLabel: "View flyer",
    tags: ["Roundtable", "Arts & Media", "Creative"]
  },
  {
    id: "wed-copilot-chat",
    day: "Wednesday",
    date: "2026-03-25",
    title: "MS Copilot Chat Training",
    startTime: "9:00 am",
    endTime: "10:30 am",
    location: "Virtual",
    modality: "Online",
    modOrTrainerLabel: "Trainer",
    modOrTrainer: "Britney Norris (IT)",
    notes: "",
    link: null,
    tags: ["Training", "Tools"]
  },
  {
    id: "wed-create-or-generate",
    day: "Wednesday",
    date: "2026-03-25",
    title: "Create or Generate: Crafting and Gossiping About Generative AI",
    startTime: "6:30 pm",
    endTime: "8:30 pm",
    location: "Newton Gresham Library Main Lobby",
    modality: "In person",
    modOrTrainer: "",
    notes: "No registration needed.",
    link: null,
    tags: ["Library", "Evening event"]
  },

  // Thursday, March 26
  {
    id: "thu-prompt-workshop",
    day: "Thursday",
    date: "2026-03-26",
    title: "Prompting for Precision: Designing Effective AI Queries in Higher Education",
    startTime: "10:00 am",
    endTime: "11:00 am",
    location: "Zoom",
    modality: "Online",
    description: "Learn how to write effective AI prompts to support teaching, research, and faculty workflows. This session provides practical strategies and ready-to-use examples you can apply immediately.",
    modOrTrainer: "Moderator Dr. Ashley L. Brittain, SHSU AI Faculty Fellow, Assistant Professor-School of Teaching and Learning",
    notes: "",
    link: "https://shsu.zoom.us/j/5345325402",
    flyerLink: "Ashleyflyer.pdf",
    flyerLabel: "View flyer",
    tags: ["Workshop", "Faculty", "Prompting"]
  },
  {
    id: "thu-middle-ground",
    day: "Thursday",
    date: "2026-03-26",
    title: "Middle Ground: Bearkats Talk AI",
    startTime: "11:00 am",
    endTime: "1:00 pm",
    location: "LSC 230A&B or 241A&B",
    modality: "In person",
    modOrTrainer: "",
    notes: "Students and a faculty panel (Syed, Bina, Yingying).",
    link: null,
    tags: ["Panel", "Students", "Faculty"]
  },
  {
    id: "thu-blackboard-design-assistant",
    day: "Thursday",
    date: "2026-03-26",
    title: "AI Design Assistant for Blackboard Webinar",
    startTime: "1:00 pm",
    endTime: null,
    location: "Online",
    modality: "Online",
    modOrTrainer: "SHSU Online Instructional Development and Support",
    notes: "",
    linkLabel: "Register Here",
    link: "https://wkf.ms/4rP6d1Z",
    tags: ["Webinar", "Blackboard", "Faculty support"]
  },
  {
    id: "thu-academic-affairs-panel",
    day: "Tuesday",
    date: "2026-03-24",
    title: "Academic Integrity in the Age of AI Webinar",
    startTime: "12:00 pm",
    endTime: null,
    location: "Online",
    modality: "Online",
    modOrTrainer: "SHSU Online Instructional Development and Support",
    notes: "",
    linkLabel: "Register Here",
    link: "https://wkf.ms/4rP6d1Z",
    tags: ["Webinar", "Academic integrity", "Faculty support"]
  },

  // Friday, March 27
  {
    id: "thu-licensed-copilot",
    day: "Friday",
    date: "2026-03-27",
    title: "Licensed MS Copilot Training",
    startTime: "9:00 am",
    endTime: "10:30 am",
    location: "Teams",
    modality: "Online",
    modOrTrainer: "Trainer: Britney Norris (IT)",
    notes: "",
    link: null,
    tags: ["Training", "Tools"]
